#!/usr/bin/lua
-- Copyright © 2012 Zachary Catlin. See LICENSE for terms.

-- In the source tree, the source files for the packages we want to load
-- are in the same directory as this file; when installed onto a system,
-- they will probably be in a different directory altogether.
-- Accordingly, the installation script will modify the following line:
package.path = string.gsub(arg[0], '[^/\\]*$', '') .. '?.lua'

require('limeparse')

local argc, i = table.maxn(arg), 1
local input, output

-- Options processing
while i <= argc do
  if arg[i] == '-o' then
    if output ~= nil then
      io.stderr:write(arg[0] .. ': Error: Multiple output files specified\n')
      os.exit(1)
    end

    i = i + 1
    output = arg[i]
  else
    if input ~= nil then
      io.stderr:write(arg[0] .. ': Error: Multiple input files specified\n')
      os.exit(1)
    end

    input = arg[i]
  end

  i = i + 1
end

--print('input = ' .. tostring(input))
--print('output = ' .. tostring(output))
